# Generated by Django 2.2.3 on 2019-12-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='emai',
        ),
        migrations.AddField(
            model_name='realtor',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
